### ISSUE TITLE
Dockerfile does not exist in node_module

### ISSUE THREAD

**Issue by hlherrera** [Suor/serverless-tesseract#1]
Dockerfile does not exist in node_module serverless_tesseract.

npm install --save serverless-tesseract

**Comment by Suor** [comment]
What command are you executing? What error do you get and when?

**Comment by aksonov** [comment]
% sls deploy

Deploying aws-ocr to stage dev (us-east-1, "default" provider)
Adding tesseract artifacts...

✖ Stack aws-ocr-dev failed to deploy (0s)
Environment: darwin, node 16.13.2, framework 3.7.9 (standalone), plugin 6.1.5, SDK 4.3.2
Credentials: Serverless Dashboard, "default" provider (https://app.serverless.com/aksonov/apps/aws-ocr/aws-ocr/dev/us-east-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: #1 [internal] load build definition from Dockerfile
#1 sha256:9de5645e5b33c85ead9caa039e544f2a36ed67e02574a62642ec7b6b56d82415
#1 transferring dockerfile: 2B done
#1 DONE 0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount502286870/Dockerfile: no such file or directory

    at run (/Users/aksonov/Documents/aws-ocr/node_modules/serverless-docker-artifacts/index.js:121:11)
    at Function.createArtifact (/Users/aksonov/Documents/aws-ocr/node_modules/serverless-docker-artifacts/index.js:33:5)
    at ServerlessTesseract.create (/Users/aksonov/Documents/aws-ocr/node_modules/serverless-tesseract/index.js:24:13)
    at before:package:createDeploymentArtifacts (/Users/aksonov/Documents/aws-ocr/node_modules/serverless-tesseract/index.js:66:62)
    at PluginManager.runHooks (/snapshot/serverless/lib/classes/plugin-manager.js:530:15)
    at PluginManager.invoke (/snapshot/serverless/lib/classes/plugin-manager.js:563:20)
    at async PluginManager.spawn (/snapshot/serverless/lib/classes/plugin-manager.js:585:5)
    at async before:deploy:deploy (/snapshot/serverless/lib/plugins/deploy.js:40:11)
    at async PluginManager.runHooks (/snapshot/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/snapshot/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/snapshot/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/snapshot/serverless/lib/serverless.js:174:5)
    at async /snapshot/serverless/scripts/serverless.js:740:9
